name: windows

services:
  windows:
    container_name: windows
    devices:
      - /dev/kvm
      - /dev/net/tun
    environment:
      VERSION: 2025
      DISK_SIZE: 128G
      RAM_SIZE: 16G
      CPU_CORES: 8
      LANGUAGE: German
      REGION: de-DE
      KEYBOARD: de-DE
    env_file:
      - /run/secrets/windows
    image: dockurr/windows:latest
    networks:
      windows:
        ipv4_address: 10.10.5.10
    ports:
      - 50050:8006/tcp
      - 50051:3389/tcp
      - 50051:3389/udp
    stop_grace_period: 2m
    volumes:
      - /mnt/bucket/apps/windows/storage:/storage:rw
      - /mnt/bucket/apps/windows/shared:/shared:rw

networks:
  windows:
    name: windows
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.10.5.0/24
